Update to build script, tag version
GTNewHorizons/Minecraft-Backpack-Mod pull request #1
Opened 2021-12-28 15:42 UTC by bombcar

2021-12-28 16:11 UTC, SinTh0r4s requested changes
.github is copied from ExampleMod. The mod releases a migration_pack.zip in releases. Please use those files instead! The files are not different, but some should not be added to every mod. We have not yet split the ExampleMod and the build script into two different repositories. 

You're getting the hang of it. Good job!

2021-12-28 16:11 UTC, SinTh0r4s commented on gradle.properties
> +gradleTokenModId = GRADLETOKEN_MODID
I found issues with replacing modName and modId for dev builds. It might be better to leave them as constants for now.

2021-12-28 16:11 UTC, SinTh0r4s commented on gradle.properties
> +#customArchiveBaseName =
Original file name is lower case. It should be kept for compatibility: `backpack`
Look for archiveBaseName in the original script or a old release jar in the pack.

2021-12-28 16:36 UTC, bombcar commented
This builds and runs butt something is wrong - it's not loading as expected in the full pack ....

2021-12-28 16:53 UTC, SinTh0r4s requested changes

2021-12-28 16:53 UTC, SinTh0r4s commented on gradle.properties
> +modName = Backpack
You need to keep the name from Constants.gradle! Don't change the names because you think it sounds better.

2021-12-28 17:09 UTC, bombcar commented
This is weird - without fingerprint it refused to load.

Perhaps we should consider updating ExampleMod to *use* the certificate/fingerprinting stuff and make it work? Otherwise we can yeet it when it causes problems.

2021-12-28 17:55 UTC, SinTh0r4s commented
Removing the certificate is the right step for now. Not sure why we would add certificates to the mods. It might produce some benefits, but also adds another dimension to maintain on the build scripts. I won't be bored enough to do that ever 😉

2021-12-28 17:55 UTC, SinTh0r4s approved these changes

2021-12-28 19:40 UTC, merged

2021-12-29 02:40 UTC, Glease commented
jar signing allows modder to rule out problems exists only in fork but not in mainline. doesn't make much sense since *we are the fork*.

2021-12-29 02:56 UTC, bombcar commented
Yeah our version numbers are our signature heheh