Add support for Soulbound enchant
GTNewHorizons/Minecraft-Backpack-Mod pull request #9
Opened 2024-05-14 14:13 UTC by TheUnderTaker11

Adds support for EnderIO's soulbound enchant on backpacks, including when they are in the backpack slot. Is implemented in basically the same exact way GTNH Adventurer's backpack mod implements this feature.
Adds config to allow disabling soulbound from working.

Tested on my private server and SP with config enabled, works as expected. Tested with config value disabled in SP, prevents you from enchanting backpack with soulbound, and even a backpack that has soulbound still drops on the ground as expected.

Let me know if you want the config value to default to false.

2024-05-16 15:53 UTC, OneEyeMaker requested changes

2024-05-16 15:53 UTC, OneEyeMaker commented on src/main/java/de/eydamos/backpack/util/EnchUtils.java
> +    public static boolean isSoulBounded(ItemStack stack) {
nitpick: `isSoulBound` would sound nicer.

2024-05-16 15:53 UTC, OneEyeMaker commented on src/main/java/de/eydamos/backpack/util/EnchUtils.java
> +                if (!bookEnch.getCompoundTagAt(1).getBoolean("id")) // only pure soulbook allowed
It's easier to just check tag count:
```suggestion
                if (!bookEnch.tagCount() == 1) // only pure soulbook allowed
```

2024-05-16 15:53 UTC, OneEyeMaker commented on src/main/java/de/eydamos/backpack/util/EnchUtils.java
> +        return false;
You can use `EnchantmentHelper` utility class to simplify code (and remove need in NBT manipulation).
```suggestion
        if (SOUL_BOUND_ID >= 0) {
            return EnchantmentHelper.getEnchantmentLevel(SOUL_BOUND_ID, stack) > 0;
        }
        return false;
```

2024-05-16 15:53 UTC, OneEyeMaker commented on src/main/java/de/eydamos/backpack/util/EnchUtils.java
> +                if (!bookEnch.getCompoundTagAt(1).getBoolean("id")) // only pure soulbook allowed
`EnchantmentHelper` can be used in this method too (if you prefer).

2024-05-17 20:37 UTC, TheUnderTaker11 commented
@OneEyeMaker Suggestions implemented and tested in SP.

2024-05-17 21:30 UTC, OneEyeMaker approved these changes

2024-05-17 21:32 UTC, merged